# Generated by Django 3.2.22 on 2023-10-23 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('day', models.DateField()),
                ('time', models.CharField(choices=[('17:00', '17:15'), ('17:30', '17:45'), ('18:00', '18:15'), ('18:30', '18:45'), ('19:00', '19:15'), ('19:30', '19:45'), ('20:00', '20:15'), ('20:30', '20:45')], max_length=10)),
                ('party_size', models.IntegerField(default=1)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
