# Generated by Django 3.2.22 on 2024-03-08 14:17

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='day',
            field=models.DateField(validators=[booking.models.validate_future_date]),
        ),
    ]
