# Generated by Django 3.2.22 on 2023-10-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='party_size',
            field=models.CharField(choices=[('p_num1', '1'), ('p_num2', '2'), ('p_num3', '3'), ('p_num4', '4'), ('p_num5', '5'), ('p_num6', '6'), ('p_num7', '7'), ('p_num8', '8'), ('p_num9', '9'), ('p_num10', '10')], max_length=25),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.CharField(choices=[('17:00', '17:15'), ('17:30', '17:45'), ('18:00', '18:15'), ('18:30', '18:45'), ('19:00', '19:15'), ('19:30', '19:45'), ('20:00', '20:15'), ('20:30', '20:45')], max_length=25),
        ),
    ]
